// Enkel font-databas. Lägg till fler rader vid behov.
// url = Google Fonts CSS (eller tom sträng om den redan finns i index).
const FONTS = [
  {label:'Special Elite (skrivmaskin)', value:"'Special Elite', cursive", url:''},
  {label:'IM Fell English (gammaldags)', value:"'IM Fell English', serif", url:''},

  {label:'Merriweather', value:"'Merriweather', serif",
   url:"https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&display=swap"},
  {label:'Roboto Slab', value:"'Roboto Slab', serif",
   url:"https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;700&display=swap"},
  {label:'Dancing Script', value:"'Dancing+Script', cursive",
   url:"https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;600&display=swap"},
  {label:'Amatic SC', value:"'Amatic SC', cursive",
   url:"https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap"},
  {label:'Cinzel', value:"'Cinzel', serif",
   url:"https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap"},
  {label:'Patrick Hand', value:"'Patrick Hand', cursive",
   url:"https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap"},
  {label:'Cormorant Garamond', value:"'Cormorant Garamond', serif",
   url:"https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600&display=swap"},
  {label:'EB Garamond', value:"'EB Garamond', serif",
   url:"https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;600&display=swap"},
  {label:'Noto Serif', value:"'Noto Serif', serif",
   url:"https://fonts.googleapis.com/css2?family=Noto+Serif:wght@400;700&display=swap"},
  {label:'Crimson Pro', value:"'Crimson Pro', serif",
   url:"https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@400;700&display=swap"},
  {label:'Quattrocento', value:"'Quattrocento', serif",
   url:"https://fonts.googleapis.com/css2?family=Quattrocento:wght@400;700&display=swap"},
  {label:'Alegreya', value:"'Alegreya', serif",
   url:"https://fonts.googleapis.com/css2?family=Alegreya:wght@400;700&display=swap"},
  {label:'Playfair Display', value:"'Playfair Display', serif",
   url:"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap"},
  {label:'Spectral', value:"'Spectral', serif",
   url:"https://fonts.googleapis.com/css2?family=Spectral:wght@400;700&display=swap"},
  {label:'Poppins', value:"'Poppins', sans-serif",
   url:"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap"},
];
